services:
  db:
    restart: always
    image: postgres
    env_file:
      - .env
    container_name: db
    volumes:
      - pgdbdata:/var/lib.postgresql/data/
    ports:
      - "5432:5432"
  django:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: sh -c "python3 manage.py migrate && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  

volumes:
  pgdbdata: null
