# Generated by Django 4.2 on 2024-09-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=150, null=True)),
                ('github', models.CharField(blank=True, max_length=150, null=True)),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Моя информация',
                'verbose_name_plural': 'Моя информация',
                'ordering': ['my_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='projectsinfo',
            options={'ordering': ['my_order'], 'verbose_name': 'Информация о проекте', 'verbose_name_plural': 'Информация о пректах'},
        ),
        migrations.AddField(
            model_name='projectsinfo',
            name='it_field_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='projectsinfo',
            name='it_field_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='projectsinfo',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectsinfo',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='projectsinfo',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='projectsinfo',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=150)),
                ('technology_name_ru', models.CharField(max_length=150, null=True)),
                ('technology_name_en', models.CharField(max_length=150, null=True)),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('project', models.ManyToManyField(related_name='technologies', to='projects_info.projectsinfo')),
                ('project_en', models.ManyToManyField(null=True, related_name='technologies', to='projects_info.projectsinfo')),
                ('project_ru', models.ManyToManyField(null=True, related_name='technologies', to='projects_info.projectsinfo')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['my_order'],
            },
        ),
    ]
